In [21]:
import os
import xml.etree.ElementTree as ET

path = 'nnc_updated_ah\\cs\\a17.xml'
filelist = os.listdir(path)

tags = []

for file in filelist:
    filepath = os.path.join(path, file)
    print(filepath)

    tree = ET.parse(filepath)
    root = tree.getroot()

    for data in root.findall('text'):
        for value in data:
            # print(value.tag)
            if (value.tag == 'group'):
                # for group in value.findall('group'):
                for body in value.findall('body'):
                    for div in body.findall('div'):
                        for subdiv in div:
                            # print(subdiv.tag)
                            if (subdiv.tag == "head"):
                                for sentence in subdiv.findall('s'):
                                    # print(sentence.attrib)
                                    for s in sentence:
                                        # print(s.attrib)
                                        if (s.tag == "foreign"):
                                            for words in s.findall('w'):
                                                tags.append(words.attrib['ctag'])
                                                print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                        # print("\n")
                                        if (s.tag == "w"):
                                            tags.append(s.attrib['ctag'])
                                            print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                            # countTags(tags,s.attrib['ctag'])
                                    print('\n')

                            if (subdiv.tag == "p"):
                                for sentence in subdiv.findall('s'):
                                    print(sentence.attrib)
                                    for s in sentence:
                                        if (s.tag == "foreign"):
                                            for words in s.findall('w'):
                                                tags.append(words.attrib['ctag'])
                                                print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                                # countTags(tags,words.attrib['ctag'])
                                        # print("\n")
                                        if (s.tag == "w"):
                                            tags.append(s.attrib['ctag'])
                                            print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                            # countTags(tags,s.attrib['ctag'])
                                    print('\n')
            if (value.tag == 'body'):
                # for body in value.findall('body'):
                for div in value.findall('div'):
                    for subdiv in div:
                        # print(subdiv.tag)
                        if (subdiv.tag == "head"):
                            for sentence in subdiv.findall('s'):
                                print(sentence.attrib)
                                for s in sentence:
                                    # print(s.attrib)
                                    if (s.tag == "foreign"):
                                        for words in s.findall('w'):
                                            tags.append(words.attrib['ctag'])
                                            print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # countTags(tags,words.attrib['ctag'])
                                    # print("\n")
                                    if (s.tag == "w"):
                                        tags.append(s.attrib['ctag'])
                                        print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                        # countTags(tags,s.attrib['ctag'])
                                print('\n')

                        if (subdiv.tag == "p"):
                            for sentence in subdiv.findall('s'):
                                print(sentence.attrib)
                                for s in sentence:
                                    if (s.tag == "foreign"):
                                        for words in s.findall('w'):
                                            tags.append(words.attrib['ctag'])
                                            print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # countTags(tags,words.attrib['ctag'])
                                    # print("\n")
                                    if (s.tag == "w"):
                                        tags.append(s.attrib['ctag'])
                                        print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                        # countTags(tags,s.attrib['ctag'])
                                print('\n')
                                

NotADirectoryError: [WinError 267] The directory name is invalid: 'nnc_updated_ah\\cs\\a17.xml'

In [22]:
# Numbers of Tags
print(tags)
output = set()
for x in tags:
    output.add(x)
print("Number of tags:", len(output))
print(output)

NameError: name 'tags' is not defined

In [23]:
def get_features(tokens, index):
    word = tokens[index]
    pos = tokens[index + 1]
    if index == 0:
        prevword = ''
        prevpos = ''
        prevprevword = ''
        prevprevpos = ''
    elif index == 2:
        prevword = tokens[index - 2]
        prevpos = tokens[index - 1]
        prevprevword = ''
        prevprevpos = ''
    else:
        prevword = tokens[index - 2]
        prevpos = tokens[index - 1]
        prevprevword = tokens[index - 4]
        prevprevpos = tokens[index - 3]

    if index == len(tokens) - 2:
        nextword = ''
        nextpos = ''
        nextnextword = ''
        nextnextpos = ''
    elif index == len(tokens) - 4:
        nextword = tokens[index + 2]
        nextpos = tokens[index + 3]
        nextnextword = ''
        nextnextpos = ''
    else:
        nextword = tokens[index + 2]
        nextpos = tokens[index + 3]
        nextnextword = tokens[index + 4]
        nextnextpos = tokens[index + 5]

    features = {'feature': {'word': word, 'pos': pos, 'next-word': nextword, 'next-pos': nextpos,
                            'next-next-word': nextnextword,
                            'next-next-pos': nextnextpos, 'prev-word': prevword, 'prev-pos': prevpos,
                            'prev-prev-word': prevprevword,
                            'prev-prev-pos': prevprevpos}, 'pos': pos}

    return {
        'word': word,
        'pos': pos,

        'next-word': nextword,
        'next-pos': nextpos,

        'next-next-word': nextnextword,
        'nextnextpos': nextnextpos,

        'prev-word': prevword,
        'prev-pos': prevpos,

        'prev-prev-word': prevprevword,
        'prev-prev-pos': prevprevpos,
    }

def get_wordFeatures(tokens, index):
    word = tokens[index]
    # pos = tokens[index + 1]

    if index == 0:
        prevword = ''
        prevprevword = ''
    elif index == 1:
        prevword = tokens[index - 1]
        prevprevword = ''
    else:
        prevword = tokens[index - 1]
        prevprevword = tokens[index - 2]

    if index == len(tokens) - 1:
        nextword = ''
        nextnextword = ''

    elif index == len(tokens) - 2:
        nextword = tokens[index + 1]
        nextnextword = ''

    else:
        nextword = tokens[index + 1]
        nextnextword = tokens[index + 2]

    return {
        'word': word,
        # 'pos': '',

        'next-word': nextword,
        # 'next-pos': '',

        'next-next-word': nextnextword,
        # 'nextnextpos': '',

        'prev-word': prevword,
        # 'prev-pos': '',

        'prev-prev-word': prevprevword,
        # 'prev-prev-pos': '',
    }

def get_testfeatures(tokens, index):
    word = tokens[index]

    if index == 0:
        prevword = ''
        prevprevword = ''

    elif index == 2:
        prevword = tokens[index - 2]
        prevprevword = ''

    else:
        prevword = tokens[index - 2]
        prevprevword = tokens[index - 4]

    if index == len(tokens) - 2:
        nextword = ''
        nextnextword = ''

    elif index == len(tokens) - 4:
        nextword = tokens[index + 2]
        nextnextword = ''
    else:
        nextword = tokens[index + 2]
        nextnextword = tokens[index + 4]

    return {
        'word': word,
        # 'pos': '',

        'next-word': nextword,
        # 'next-pos': '',

        'next-next-word': nextnextword,
        # 'nextnextpos': '',

        'prev-word': prevword,
        # 'prev-pos': '',

        'prev-prev-word': prevprevword,
        # 'prev-prev-pos': '',

    }


In [24]:
# -*- coding: utf-8 -*-
import os
import ExtractFeatures
import xml.etree.ElementTree as ET

import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction import DictVectorizer
from sklearn import svm

path = 'nnc_updated_ah\\cs\\a07.xml'

X, y, X_test, y_test, test_sen, train_sen = [], [], [], [], [], []
temp = 0


trainFeatures = [{'prev-word': '', 'next-word': 'निर्वाचन', 'word': 'आम'}, {'prev-word': 'आम', 'next-word': 'मा', 'word': 'निर्वाचन'}, {'prev-word': 'निर्वाचन', 'next-word': 'स्पष्ट', 'word': 'मा'}, {'prev-word': 'मा', 'next-word': 'बहुमत', 'word': 'स्पष्ट'}, {'prev-word': 'स्पष्ट', 'next-word': 'ल्याए', 'word': 'बहुमत'}, {'prev-word': 'बहुमत', 'next-word': 'को', 'word': 'ल्याए'}, {'prev-word': 'ल्याए', 'next-word': 'नेपाली', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'काँग्रेस', 'word': 'नेपाली'}, {'prev-word': 'नेपाली', 'next-word': 'को', 'word': 'काँग्रेस'}, {'prev-word': 'काँग्रेस', 'next-word': 'संसदीय', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'दल', 'word': 'संसदीय'}, {'prev-word': 'संसदीय', 'next-word': 'का', 'word': 'दल'}, {'prev-word': 'दल', 'next-word': 'नेता', 'word': 'का'}, {'prev-word': 'का', 'next-word': 'को', 'word': 'नेता'}, {'prev-word': 'नेता', 'next-word': 'रुप', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'मा', 'word': 'रुप'}, {'prev-word': 'रुप', 'next-word': 'श्री', 'word': 'मा'}, {'prev-word': 'मा', 'next-word': 'गिरीजा', 'word': 'श्री'}, {'prev-word': 'श्री', 'next-word': 'प्रसाद', 'word': 'गिरीजा'}, {'prev-word': 'गिरीजा', 'next-word': 'कोइराला', 'word': 'प्रसाद'}, {'prev-word': 'प्रसाद', 'next-word': 'ले', 'word': 'कोइराला'}, {'prev-word': 'कोइराला', 'next-word': 'पन्द्रह', 'word': 'ले'}, {'prev-word': 'ले', 'next-word': 'सदस्यीय', 'word': 'पन्द्रह'}, {'prev-word': 'पन्द्रह', 'next-word': 'मन्त्रि', 'word': 'सदस्यीय'}, {'prev-word': 'सदस्यीय', 'next-word': 'परिषद', 'word': 'मन्त्रि'}, {'prev-word': 'मन्त्रि', 'next-word': 'को', 'word': 'परिषद'}, {'prev-word': 'परिषद', 'next-word': 'गठन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'गरी', 'word': 'गठन'}, {'prev-word': 'गठन', 'next-word': 'सक्नु', 'word': 'गरी'}, {'prev-word': 'गरी', 'next-word': 'भए', 'word': 'सक्नु'}, {'prev-word': 'सक्नु', 'next-word': 'पछि', 'word': 'भए'}, {'prev-word': 'भए', 'next-word': 'मुलुक', 'word': 'पछि'}, {'prev-word': 'पछि', 'next-word': 'को', 'word': 'मुलुक'}, {'prev-word': 'मुलुक', 'next-word': 'ध्यान', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'राष्ट्रिय', 'word': 'ध्यान'}, {'prev-word': 'ध्यान', 'next-word': 'सभा', 'word': 'राष्ट्रिय'}, {'prev-word': 'राष्ट्रिय', 'next-word': 'को', 'word': 'सभा'}, {'prev-word': 'सभा', 'next-word': 'गठन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'र', 'word': 'गठन'}, {'prev-word': 'गठन', 'next-word': 'त्यस', 'word': 'र'}, {'prev-word': 'र', 'next-word': 'पछि', 'word': 'त्यस'}, {'prev-word': 'त्यस', 'next-word': 'हुने', 'word': 'पछि'}, {'prev-word': 'पछि', 'next-word': 'संसद', 'word': 'हुने'}, {'prev-word': 'हुने', 'next-word': 'को', 'word': 'संसद'}, {'prev-word': 'संसद', 'next-word': 'अधिवेशन', 'word': 'को'}, {'prev-word': 'को', 'next-word': 'तिर', 'word': 'अधिवेशन'}, {'prev-word': 'अधिवेशन', 'next-word': 'केन्द्रित', 'word': 'तिर'}, {'prev-word': 'तिर', 'next-word': 'हुन', 'word': 'केन्द्रित'}, {'prev-word': 'केन्द्रित', 'next-word': 'थाले', 'word': 'हुन'}, {'prev-word': 'हुन', 'next-word': 'को', 'word': 'थाले'}, {'prev-word': 'थाले', 'next-word': 'छ', 'word': 'को'}, {'prev-word': 'को', 'next-word': '।', 'word': 'छ'}, {'prev-word': 'छ', 'next-word': '', 'word': '।'}]
trainLabels = ['JX', 'NN', 'II', 'JX', 'NN', 'VE', 'IKM', 'NN', 'NN', 'IKM', 'JX', 'NN', 'IKO', 'NN', 'IKM', 'NN', 'II', 'NN', 'NP', 'NP', 'NP', 'IE', 'MM', 'JX', 'NN', 'NN', 'IKM', 'NN', 'VR', 'VI', 'VE', 'II', 'NN', 'IKM', 'NN', 'JX', 'NN', 'IKM', 'NN', 'CC', 'DDX', 'II', 'VN', 'NN', 'IKM', 'NN', 'II', 'JX', 'VI', 'VE', 'IKM', 'VVYN1', 'YF']
test_feat =[]
test = ['संसद', 'को', 'अधिवेशन', 'आषाढ', 'को', 'शुरु', 'मा', 'हुने', 'राष्ट्रियसभा', 'को', 'गठन', 'यै', 'महिना', 'मा', 'भईसक्ने', 'चीन-सोभियत', 'सीमा', 'मा', 'बढी', 'सबल', 'सुरक्षा']
# test = [{'pos': 'IKM', 'prev-prev-word': 'अधिवेशन', 'word': 'को', 'prev-word': 'आषाढ', 'prev-pos': 'NN', 'next-next-word': 'मा', 'prev-prev-pos': 'NN', 'next-pos': 'NN', 'next-word': 'शुरु', 'nextnextpos': 'II'}]
for x in range(0, len(test)):
    test_feat.append(ExtractFeatures.get_wordFeatures(test, x))
print(test, test_feat)


vec = DictVectorizer(sparse=False)
X_arr = vec.fit_transform(trainFeatures)
print("Converting word features into Numpy arrays")
print(X_arr)
XTest_arr = vec.fit_transform(test_feat)
print("Converting test word features into Numpy arrays")
print(XTest_arr)


print(X_arr.shape[1], XTest_arr.shape[1])
clf = svm.SVC(kernel="linear")
clf.fit(X_arr, trainLabels)

print("Support vectors")
print(clf.support_vectors_)
with open("support.txt", "wb") as f:
    np.savetxt(f, clf.support_vectors_)
    f.close()
print("No of Support Vectors")
print(clf.n_support_)
print("Support vector indices")
print(clf.support_)

['संसद', 'को', 'अधिवेशन', 'आषाढ', 'को', 'शुरु', 'मा', 'हुने', 'राष्ट्रियसभा', 'को', 'गठन', 'यै', 'महिना', 'मा', 'भईसक्ने', 'चीन-सोभियत', 'सीमा', 'मा', 'बढी', 'सबल', 'सुरक्षा'] [{'word': 'संसद', 'next-word': 'को', 'next-next-word': 'अधिवेशन', 'prev-word': '', 'prev-prev-word': ''}, {'word': 'को', 'next-word': 'अधिवेशन', 'next-next-word': 'आषाढ', 'prev-word': 'संसद', 'prev-prev-word': ''}, {'word': 'अधिवेशन', 'next-word': 'आषाढ', 'next-next-word': 'को', 'prev-word': 'को', 'prev-prev-word': 'संसद'}, {'word': 'आषाढ', 'next-word': 'को', 'next-next-word': 'शुरु', 'prev-word': 'अधिवेशन', 'prev-prev-word': 'को'}, {'word': 'को', 'next-word': 'शुरु', 'next-next-word': 'मा', 'prev-word': 'आषाढ', 'prev-prev-word': 'अधिवेशन'}, {'word': 'शुरु', 'next-word': 'मा', 'next-next-word': 'हुने', 'prev-word': 'को', 'prev-prev-word': 'आषाढ'}, {'word': 'मा', 'next-word': 'हुने', 'next-next-word': 'राष्ट्रियसभा', 'prev-word': 'शुरु', 'prev-prev-word': 'को'}, {'word': 'हुने', 'next-word': 'राष्ट्रियसभा', 'next-

In [25]:
import os
import ExtractFeatures
import xml.etree.ElementTree as ET

path = 'nnc_updated_ah\\cs\\a17.xml'

X, y, X_test, y_test, test_sen = [], [], [], [], []
temp = 0

tree = ET.parse(path)
root = tree.getroot()
single_sentence = []

for data in root.findall('text'):
            for value in data:
                # print(value.tag)
                if (value.tag == 'group'):
                    # for group in value.findall('group'):
                    for body in value.findall('body'):
                        for div in body.findall('div'):
                            for subdiv in div:
                                # print(subdiv.tag)
                                if (subdiv.tag == "head"):

                                    for sentence in subdiv.findall('s'):
                                        print(sentence.attrib)
                                        single_sentence = []
                                        for s in sentence:
                                            # print(s.attrib)
                                            if (s.tag == "foreign"):
                                                for words in s.findall('w'):
                                                    print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # print("\n")
                                            if (s.tag == "w"):
                                                # print("%s %s" % (s.text, s.attrib['ctag']), '', end=''),
                                                single_sentence.append(s.text)
                                                single_sentence.append(s.attrib['ctag'])
                                                test_sen.append(s.text)
                                                y_test.append(s.attrib['ctag'])
                                        print(single_sentence)

                                        for x in range(0, len(single_sentence), 2):
                                            # print(get_features(single_sentence,x))
                                            X_test.append(ExtractFeatures.get_testfeatures(single_sentence, x))
                                #         # print('\n')
                                # print(len(single_sentence))
                                if (subdiv.tag == "p"):
                                    for sentence in subdiv.findall('s'):
                                        # print(sentence.attrib)
                                        single_sentence = []
                                        for s in sentence:
                                            if (s.tag == "foreign"):
                                                for words in s.findall('w'):
                                                  print("%s/%s" % (words.text, words.attrib['ctag']), '', end=''),
                                            # print("\n")
                                            if (s.tag == "w"):
                                                temp = temp+1
                                                # print("%s/%s" % (s.text, s.attrib['ctag']), '', end=''),
                                                single_sentence.append(s.text)
                                                single_sentence.append(s.attrib['ctag'])
                                                y.append(s.attrib['ctag'])

                                        for x in range(0, len(single_sentence), 2):
                                            X.append(ExtractFeatures.get_testfeatures(single_sentence, x))
                                            # temp = temp + 1

    # print(temp)
print(len(X), len(X_test))
print(len(y), len(y_test))

{'n': '1'}
['संसद', 'NN', 'को', 'IKM', 'अधिवेशन', 'NN', 'आषाढ', 'NN', 'को', 'IKM', 'शुरु', 'NN', 'मा', 'II', 'हुने', 'VN', 'राष्ट्रियसभा', 'NN', 'को', 'IKM', 'गठन', 'NN', 'यै', 'DDX', 'महिना', 'NN', 'मा', 'II', 'भईसक्ने', 'VN']
{'n': '18'}
['चीन-सोभियत', 'NP', 'सीमा', 'NN', 'मा', 'II', 'बढी', 'JX', 'सबल', 'JX', 'सुरक्षा', 'NN']
{'n': '36'}
['राष्ट्रिय', 'JX', 'जनगणना', 'NN', 'को', 'IKM', 'महत्व', 'NN']
{'n': '46'}
['भारत', 'NP', 'र', 'CC', 'नेपाल', 'NP', 'को', 'IKM', 'वार्ता', 'NN', 'विवाद', 'NN', 'को', 'IKM', 'जाल', 'NN', 'मा', 'II']
{'n': '64'}
['राष्ट्र', 'NN', 'बैंक', 'NN', 'मा', 'II', 'कर्मचारी', 'NN', 'निलम्बित', 'JX']
{'n': '81'}
['त्रिभुवन', 'NP', 'विश्वविद्यालय', 'NN', 'मा', 'II', 'राजिनामा', 'NN', 'को', 'IKM', 'लहर', 'NN']
{'n': '82'}
['उपकुलपति', 'NN', 'र', 'CC', 'पदाधिकारी', 'NN', 'हरु', 'IH', 'को', 'IKM', 'नयाँ', 'JX', 'नियुक्ति', 'NN', 'हुने', 'VN', '?', 'YF']
{'n': '91'}
['मुस्लिम', 'NN', 'र', 'CC', 'हिन्दु', 'NN', 'को', 'IKM', 'दंगा', 'NN']
{'n': '92'}
['पार्टी', 'NN', 

In [26]:
# Calculate accuracy
from sklearn.feature_extraction import DictVectorizer
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline

clf = Pipeline([
            ('vectorizer', DictVectorizer(sparse=False)),
            ('classifier', LinearSVC())
        ])
clf.fit(X[:50000],y[:50000])

y_predict = (clf.predict(X_test))
print(test_sen)
print(y_predict)
accuracy = clf.score(X_test, y_test)
print("Accuracy:", accuracy * 100, '%')

for x in range(0, len(test_sen)):
     print("%s/%s" % (test_sen[x], y_predict[x]),'', end='')

import pickle
pickle.dump(clf, open("RESULT.pickle", "wb"))

['संसद', 'को', 'अधिवेशन', 'आषाढ', 'को', 'शुरु', 'मा', 'हुने', 'राष्ट्रियसभा', 'को', 'गठन', 'यै', 'महिना', 'मा', 'भईसक्ने', 'चीन-सोभियत', 'सीमा', 'मा', 'बढी', 'सबल', 'सुरक्षा', 'राष्ट्रिय', 'जनगणना', 'को', 'महत्व', 'भारत', 'र', 'नेपाल', 'को', 'वार्ता', 'विवाद', 'को', 'जाल', 'मा', 'राष्ट्र', 'बैंक', 'मा', 'कर्मचारी', 'निलम्बित', 'त्रिभुवन', 'विश्वविद्यालय', 'मा', 'राजिनामा', 'को', 'लहर', 'उपकुलपति', 'र', 'पदाधिकारी', 'हरु', 'को', 'नयाँ', 'नियुक्ति', 'हुने', '?', 'मुस्लिम', 'र', 'हिन्दु', 'को', 'दंगा', 'पार्टी', 'हरु', 'को', 'दिबालियापन', 'को', 'परिणाम']
['NN' 'IKM' 'NN' 'NN' 'IKM' 'NN' 'II' 'VN' 'NN' 'IKM' 'NN' 'NN' 'NN' 'II'
 'YF' 'NP' 'NN' 'II' 'NN' 'NN' 'YF' 'JX' 'NN' 'IKM' 'NN' 'NP' 'CC' 'NP'
 'IKM' 'NN' 'NN' 'IKM' 'NN' 'II' 'NN' 'NN' 'II' 'NN' 'YF' 'DDX' 'NN' 'II'
 'NN' 'IKM' 'YF' 'NN' 'CC' 'NN' 'IH' 'IKM' 'JX' 'NN' 'VN' 'YF' 'NN' 'CC'
 'NN' 'IKM' 'NN' 'NN' 'IH' 'IKM' 'NN' 'IKM' 'YF']
Accuracy: 86.15384615384616 %
संसद/NN को/IKM अधिवेशन/NN आषाढ/NN को/IKM शुरु/NN मा/II हुने/VN राष्ट्

In [27]:
# Classification report\n",
from sklearn.metrics import classification_report
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

          CC       1.00      1.00      1.00         3
         DDX       0.00      0.00      0.00         1
          IH       1.00      1.00      1.00         2
          II       1.00      1.00      1.00         6
         IKM       1.00      1.00      1.00        11
          JX       1.00      0.40      0.57         5
          NN       0.90      0.90      0.90        29
          NP       1.00      0.75      0.86         4
          VN       1.00      0.67      0.80         3
          YF       0.17      1.00      0.29         1

    accuracy                           0.86        65
   macro avg       0.81      0.77      0.74        65
weighted avg       0.93      0.86      0.88        65



In [28]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_test, y_predict)
print(conf_matrix)

[[ 3  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  1  0  0  0]
 [ 0  0  2  0  0  0  0  0  0  0]
 [ 0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0 11  0  0  0  0  0]
 [ 0  0  0  0  0  2  2  0  0  1]
 [ 0  0  0  0  0  0 26  0  0  3]
 [ 0  1  0  0  0  0  0  3  0  0]
 [ 0  0  0  0  0  0  0  0  2  1]
 [ 0  0  0  0  0  0  0  0  0  1]]


In [29]:
# Cross-tabulated Confusion Matrix\n",
# Create a DataFrame
import pandas as pd
data = {'Actual': y_test, 'Predicted': y_predict}
df = pd.DataFrame(data)
# Create the confusion matrix
conf_matrix = pd.crosstab(df['Actual'], df['Predicted'], rownames=['Actual'], colnames=['Predicted'])
print(conf_matrix)

Predicted  CC  DDX  IH  II  IKM  JX  NN  NP  VN  YF
Actual                                             
CC          3    0   0   0    0   0   0   0   0   0
DDX         0    0   0   0    0   0   1   0   0   0
IH          0    0   2   0    0   0   0   0   0   0
II          0    0   0   6    0   0   0   0   0   0
IKM         0    0   0   0   11   0   0   0   0   0
JX          0    0   0   0    0   2   2   0   0   1
NN          0    0   0   0    0   0  26   0   0   3
NP          0    1   0   0    0   0   0   3   0   0
VN          0    0   0   0    0   0   0   0   2   1
YF          0    0   0   0    0   0   0   0   0   1


In [30]:
# Calculate macro/micro precision, recall & f1-score
from sklearn.metrics import precision_score, recall_score, f1_score
precision_macro = precision_score(y_test, y_predict, average='macro')
precision_micro = precision_score(y_test, y_predict, average='micro')

recall_macro = recall_score(y_test, y_predict, average='macro')
recall_micro = recall_score(y_test, y_predict, average='micro')

f1_macro = f1_score(y_test, y_predict, average='macro')
f1_micro = f1_score(y_test, y_predict, average='micro')

# Print the results
print("Macro Precision Score :",  precision_macro*100, '%')
print("Micro Precision Score :", precision_micro*100, '%')

print("Macro Recall Score :", recall_macro*100, '%')
print("Micro Recall Score :", recall_micro*100, '%')

print("Macro F1 Score :", f1_macro*100, '%')
print("Micro F1 Score :", f1_micro*100, '%')

Macro Precision Score : 80.63218390804596 %
Micro Precision Score : 86.15384615384616 %
Macro Recall Score : 77.13218390804599 %
Micro Recall Score : 86.15384615384616 %
Macro F1 Score : 74.10837438423646 %
Micro F1 Score : 86.15384615384615 %
